language: node_js
sudo: false
node_js:
  - "6"
  - "7"

env:
  global:
    - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - g++-4.8 --version

script:
  - npm run check_format
  - npm run test_travis
